export const FETCH_ALLRESTAURANT_REQUEST = 'FETCH_ALLRESTAURANT_REQUEST'
export const FETCH_ALLRESTAURANT_SUCCESS = 'FETCH_ALLRESTAURANT_SUCCESS'
export const FETCH_ALLRESTAURANT_ERROR = 'FETCH_ALLRESTAURANT_ERROR'
